joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

motor1_effort_controller:
  type: effort_controllers/JointEffortController
  joint: motor1
  pid: {p: 100.0, i: 0.0, d: 1.0}

motor2_effort_controller:
  type: effort_controllers/JointEffortController
  joint: motor2
  pid: {p: 100.0, i: 0.0, d: 1.0}

motor3_effort_controller:
  type: effort_controllers/JointEffortController
  joint: motor3
  pid: {p: 100.0, i: 0.0, d: 1.0}

motor4_effort_controller:
  type: effort_controllers/JointEffortController
  joint: motor4
  pid: {p: 100.0, i: 0.0, d: 1.0}

motor5_effort_controller:
  type: effort_controllers/JointEffortController
  joint: motor5
  pid: {p: 100.0, i: 0.0, d: 1.0}

motor6_effort_controller:
  type: effort_controllers/JointEffortController
  joint: motor6
  pid: {p: 100.0, i: 0.0, d: 1.0}
